## Step 1: Base image
#FROM openjdk:21-jdk-slim
#
## Step 2: Set working directory inside container
#WORKDIR /app
#
## Step 3: Copy built jar file into container
#COPY target/account-0.0.1-SNAPSHOT.jar app.jar
#
## Step 4: Expose port (optional - for documentation only)
#EXPOSE 8083
#
## Step 5: Run jar
#ENTRYPOINT ["java", "-jar", "app.jar"]
